services:
  auth:
    build: 
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: auth
    ports:
      - "8087:8080"
    depends_on:
      - postgres
    environment:
      SERVICE_URL: http://auth:8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "683951"
      DB_NAME: wch
      DB_SSLMODE: disable
      JWT_SECRET: secret
      JWT_DURATION: 120
      USERS_SERVICE_ADDR: users:8080
    networks:
      - micro-net

  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    container_name: users
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - auth
    environment:
      SERVICE_URL: http://users:8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "683951"
      DB_NAME: wch
      DB_SSLMODE: disable
      JWT_SECRET: secret
      JWT_DURATION: 120
    networks:
      - micro-net

  chats:
    build:
      context: .
      dockerfile: services/chats/Dockerfile
    container_name: chats
    ports:
      - "8085:8080"
    depends_on:
      - postgres
      - auth
    environment:
      SERVICE_URL: http://chats:8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "683951"
      DB_NAME: wch
      DB_SSLMODE: disable
      JWT_SECRET: secret
      JWT_DURATION: 120
      USERS_SERVICE_ADDR: users:8080
    networks:
      - micro-net

  msgs:
    build:
      context: .
      dockerfile: services/msgs/Dockerfile
    container_name: msgs
    ports:
      - "8086:8080"
    depends_on:
      - postgres
      - auth
      - kafka
    environment:
      SERVICE_URL: http://msgs:8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "683951"
      DB_NAME: wch
      DB_SSLMODE: disable
      JWT_SECRET: secret
      JWT_DURATION: 120
      CHATS_SERVICE_ADDR: chats:8080
      KAFKA_BROKERS: "kafka:9092"
    networks:
      - micro-net

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "683951"
      POSTGRES_DB: wch
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - micro-net
  kafka:
      image: confluentinc/cp-kafka
      hostname: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
networks:
  micro-net:
    driver: bridge

volumes:
  pgdata: